name: scoreboard
description: A new Flutter package project.

environment:
  sdk: '>=2.17.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+7
  flutter_mobx: ^2.0.6+3
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  dio: ^4.0.6
  intl: ^0.18.0
  webview_flutter: ^3.0.4
  connectivity_plus:
  json_annotation: ^4.7.0
  shimmer: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  mobx_codegen: ^2.0.7+2
  json_serializable: ^6.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  assets:
    - assets/
    - assets/hostel_image.jpg
    - assets/logos/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#  fonts:
#   - family: SBIcons
#     fonts:
#       - asset: assets/SBIcons.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
